### ISSUE TITLE
Consider adding polars

### ISSUE THREAD

**Issue by jrothbaum** [clibassi/python-packages-for-applied-economists#1]
It's a ton faster than pandas and I think much easier to use. Also easier to come to from R's tidyverse syntax.

**Comment by clibassi** [comment]
Thank you for this suggestion! I've created PR #2 to add Polars and other high-performance DataFrame libraries to the guide. The PR includes a new DataFrame Libraries section that covers Polars, Datatable, and Vaex.

**Comment by jrothbaum** [comment]
Another useful set of benchmarks, Fwiw: https://duckdblabs.github.io/db-benchmark/
